// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUKDVXJ5qmmsJhdRzp8Qd36ENzEKDZeM',
    appId: '1:294687460747:web:1291ab2da691817231b38e',
    messagingSenderId: '294687460747',
    projectId: 'ayajojoimane',
    authDomain: 'ayajojoimane.firebaseapp.com',
    storageBucket: 'ayajojoimane.firebasestorage.app',
    measurementId: 'G-CE9ZSPBHHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4L7Bj3Ya6pdfDvFVVXE63hmIUxORBNKo',
    appId: '1:294687460747:android:c21712084599c30d31b38e',
    messagingSenderId: '294687460747',
    projectId: 'ayajojoimane',
    storageBucket: 'ayajojoimane.firebasestorage.app',
  );

}